import { environment } from 'src/environments/environment';

export const API = {
  rootURL: environment.apiRoot,
  baseUrl: environment.baseUrl,
  zauto_bot_url: environment.zauto_bot_url + 'app/embedding/',
  platformUrl: `${environment.baseUrl}zautobot?botid={{agentId}}&campaign={{selectedCampaign}}`,
  main: {
    auth: 'api/auth/login',
    verify: 'api/auth/verify',
    register: 'api/registration',
    password: 'api/password',
    user: 'api/users',
    bots: 'api/bots',
    lead: 'api/leads',
    leadAgent: 'api/:agentId/leads',
    leadConfig: 'api/:id/lead-configs',
    visitor: 'api/visitors',
    agentVisitor: 'api/:id/visitors',
    conversation: 'api/conversations',
    agentConversation: 'api/:id/conversations',
    agent: 'api/agents',
    agentAvailability: 'api/agents/availability',
    agentChat: 'api/agents/:agentId/chat/:convId',
    agentPrompt: 'api/agent-prompts',
    site: 'api/sites',
    orgUser: 'api/organization/users',
    platform: 'api/platforms',
    orgPlatform: 'api/org-platforms',
    campaign: 'api/campaigns',
    agentCampaign: 'api/:agentId/campaigns',
    stages: 'api/stages',
    agentStages: 'api/:agentId/stages',
    dashboard: 'api/dashboards',
    launchAvatar: 'api/agents/launchAvatar',
    usage: 'api/account/usage',
    orgSmtpConfig: 'api/organization/smtpconfig',
    cta: 'api/cta',
    oauth: 'api/oauth',
    oauthStateToken: 'api/oauth/state',
    oauthCallback: 'api/oauth/{{provider}}/callback',
    oauthProfile: 'api/oauth/{{provider}}/profile',
    oauthRevoke: 'api/oauth/{{provider}}/revoke',
    orgTool: 'api/org-tools',
    crmKeyMapping: 'api/crm-key-maping/{{toolId}}',
    crmProperties: 'api/crm-key-maping/properties/{{provider}}',
    externalApi: 'api/external-apis',
    externalApiKeymapping: 'api/{{externalApiId}}/external-api-keymapping',
    schedule: 'api/availability-schedule',
    googleCalendar: 'api/google-calendar',
    calendar: 'api/calendar',
    fileManager: 'api/file-manager',
    promptTemplate: 'api/prompt-template',
    leadCategory: 'api/lead-categories',
    formbuilder: 'api/form-builder',
    account: 'api/accounts',
  },
  dev: {},
};
