version: '3.8'

services:
  base:
    image: ghcr.io/zautoai/converto_base:dev
    networks:
      - redis-net
    volumes:
      - app_uploads:/usr/src/uploads
      - app_images:/usr/src/public/images
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always  # Restart policy for the Node app.

  crm:
     image: ghcr.io/zautoai/converto_crm:dev
    networks:
      - redis-net
    ports:
      - "3030:3001"

  redis:
    image: redis:latest
    command: redis-server --requirepass REDIS_PASSWORD_PLACEHOLDER
    networks:
      - redis-net
    expose:
      - "6379"
    volumes:
      - redis_vol:/data
    restart: always


networks:
  redis-net:
    driver: bridge

volumes:
  redis_vol:
    driver: local
  app_uploads:
    driver: local
  app_images:
    driver: local
