export const SEGMENT_CATEGORY = [
    { "name": "Industry", "description": "Various industry sectors", "color": "#A52A2A" },
    { "name": "Country", "description": "Different countries", "color": "#0000FF" },
    { "name": "Revenue", "description": "Revenue ranges of companies", "color": "#008000" },
    { "name": "Company size", "description": "Company sizes based on number of employees", "color": "#FF0000" },
    { "name": "Decision maker", "description": "Different levels of decision makers within companies", "color": "#808080" }
]

export const SEGMENT = {
    "Industry": [
        { "name": "Manufacturing", "description": "Manufacturing sector" },
        { "name": "Automotive", "description": "Automotive industry" },
        { "name": "Healthcare and Pharmaceuticals", "description": "Healthcare and pharmaceutical sector" },
        { "name": "Information Technology (IT) and Software", "description": "IT and software industry" },
        { "name": "Financial Services and Banking", "description": "Financial services and banking sector" },
        { "name": "Retail and E-commerce", "description": "Retail and e-commerce sector" },
        { "name": "Telecommunications", "description": "Telecommunications industry" },
        { "name": "Energy and Utilities", "description": "Energy and utilities sector" },
        { "name": "Construction and Engineering", "description": "Construction and engineering sector" },
        { "name": "Transportation and Logistics", "description": "Transportation and logistics sector" },
        { "name": "Professional Services (Consulting, Accounting, Legal)", "description": "Professional services including consulting, accounting, and legal" },
        { "name": "Education", "description": "Education sector" },
        { "name": "Hospitality and Tourism", "description": "Hospitality and tourism industry" },
        { "name": "Agriculture and Food Processing", "description": "Agriculture and food processing sector" },
        { "name": "Media and Entertainment", "description": "Media and entertainment industry" },
        { "name": "Real Estate", "description": "Real estate sector" },
        { "name": "Non-profit Organizations", "description": "Non-profit organizations" },
        { "name": "Government and Public Sector", "description": "Government and public sector" }
    ],
    "Country": [
        { "name": "United States", "description": "USA" },
        { "name": "Canada", "description": "Canada" },
        { "name": "United Kingdom", "description": "UK" },
        { "name": "Germany", "description": "Germany" },
        { "name": "France", "description": "France" },
        { "name": "Japan", "description": "Japan" },
        { "name": "China", "description": "China" },
        { "name": "India", "description": "India" },
        { "name": "Australia", "description": "Australia" },
        { "name": "Brazil", "description": "Brazil" },
        { "name": "Mexico", "description": "Mexico" },
        { "name": "Russia", "description": "Russia" },
        { "name": "South Africa", "description": "South Africa" },
        { "name": "United Arab Emirates", "description": "UAE" },
        { "name": "Saudi Arabia", "description": "Saudi Arabia" },
        { "name": "Singapore", "description": "Singapore" },
        { "name": "Switzerland", "description": "Switzerland" },
        { "name": "Netherlands", "description": "Netherlands" },
        { "name": "Sweden", "description": "Sweden" },
        { "name": "Italy", "description": "Italy" }
    ],
    "Revenue": [
        { "name": "<$1 million", "description": "Less than $1 million" },
        { "name": "$1 million - $5 million", "description": "$1 million to $5 million" },
        { "name": "$5 million - $10 million", "description": "$5 million to $10 million" },
        { "name": "$10 million - $25 million", "description": "$10 million to $25 million" },
        { "name": "$25 million - $50 million", "description": "$25 million to $50 million" },
        { "name": "$50 million - $100 million", "description": "$50 million to $100 million" },
        { "name": "$100 million - $500 million", "description": "$100 million to $500 million" },
        { "name": "$500 million - $1 billion", "description": "$500 million to $1 billion" },
        { "name": "$1 billion - $5 billion", "description": "$1 billion to $5 billion" },
        { "name": "$5 billion - $10 billion", "description": "$5 billion to $10 billion" },
        { "name": ">$10 billion", "description": "More than $10 billion" }
    ],
    "Company size": [
        { "name": "1-10 employees", "description": "1 to 10 employees" },
        { "name": "11-50 employees", "description": "11 to 50 employees" },
        { "name": "51-100 employees", "description": "51 to 100 employees" },
        { "name": "101-250 employees", "description": "101 to 250 employees" },
        { "name": "251-500 employees", "description": "251 to 500 employees" },
        { "name": "501-1000 employees", "description": "501 to 1000 employees" },
        { "name": "1001-5000 employees", "description": "1001 to 5000 employees" },
        { "name": "5001-10000 employees", "description": "5001 to 10000 employees" },
        { "name": "10001-25000 employees", "description": "10001 to 25000 employees" },
        { "name": "25001-50000 employees", "description": "25001 to 50000 employees" },
        { "name": "50001-100000 employees", "description": "50001 to 100000 employees" },
        { "name": ">100000 employees", "description": "More than 100000 employees" }
    ],
    "Decision maker": [
        { "name": "Chief Executive Officer (CEO)", "description": "Top executive responsible for overall management" },
        { "name": "Chief Operating Officer (COO)", "description": "Executive responsible for day-to-day operations" },
        { "name": "Chief Financial Officer (CFO)", "description": "Executive responsible for financial planning and management" },
        { "name": "Chief Information Officer (CIO)", "description": "Executive responsible for information technology and systems" },
        { "name": "Chief Marketing Officer (CMO)", "description": "Executive responsible for marketing activities" },
        { "name": "Chief Technology Officer (CTO)", "description": "Executive responsible for technological development and strategy" },
        { "name": "Vice President of Operations", "description": "Senior executive overseeing operations" },
        { "name": "Vice President of Sales", "description": "Senior executive overseeing sales" },
        { "name": "Vice President of Marketing", "description": "Senior executive overseeing marketing" },
        { "name": "Vice President of Product", "description": "Senior executive overseeing product development" },
        { "name": "Vice President of Information Technology", "description": "Senior executive overseeing IT" },
        { "name": "Director of Human Resources", "description": "Executive responsible for HR" },
        { "name": "Director of Finance", "description": "Executive responsible for financial planning" },
        { "name": "Director of Procurement", "description": "Executive responsible for procurement and sourcing" },
        { "name": "Operations Manager", "description": "Manager overseeing daily operations" },
        { "name": "Sales Manager", "description": "Manager overseeing sales teams and strategies" },
        { "name": "Marketing Manager", "description": "Manager overseeing marketing teams and campaigns" },
        { "name": "Product Manager", "description": "Manager overseeing product development and strategy" },
        { "name": "IT Manager", "description": "Manager overseeing IT infrastructure and teams" },
        { "name": "HR Manager", "description": "Manager overseeing human resources activities" },
        { "name": "Finance Manager", "description": "Manager overseeing financial activities and planning" },
        { "name": "Procurement Manager", "description": "Manager overseeing procurement processes" },
        { "name": "Data Analyst", "description": "Specialist analyzing data to inform business decisions" },
        { "name": "Business Analyst", "description": "Specialist analyzing business processes and requirements" },
        { "name": "Project Manager", "description": "Specialist overseeing project planning and execution" },
        { "name": "Software Developer", "description": "Specialist developing software solutions" },
        { "name": "Network Administrator", "description": "Specialist managing and maintaining network infrastructure" },
        { "name": "Supply Chain Specialist", "description": "Specialist managing supply chain processes" },
        { "name": "Compliance Officer", "description": "Specialist ensuring regulatory and policy compliance" }
    ]
}