name: Docker CI/CD for Demo

on:
  push:
    branches: [demo]
    paths:
      - 'base/**'
      - 'crm/**'
    tags:
      - 'v*'
  pull_request:
    branches: [demo]
    paths:
      - 'base/**'
      - 'crm/**'

permissions:
  id-token: write
  contents: read

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.DEV_GITHUB_USER }}
          password: ${{ env.DEV_GITHUB_TOKEN }}

      - name: Build and push Docker image for base
        if: contains(github.event.head_commit.message, 'base')
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64/v8
          context: ./base
          file: ./base/Dockerfile
          tags: |
            ghcr.io/zautoai/converto:demo-base${{ github.sha }}
            ghcr.io/zautoai/converto:demo-base
          build-args: |
            APOLLO_API_KEY=${{ env.DEMO_APOLLO_API_KEY }}
            AWS_ACCESS_KEY_ID=${{ env.DEMO_AWS_ACCESS_KEY_ID }}
            AWS_REGION=${{ env.DEMO_AWS_REGION }}
            AWS_SECRET_ACCESS_KEY=${{ env.DEMO_AWS_SECRET_ACCESS_KEY }}
            CHROMA_AUTH_CREDENTIALS=${{ env.DEMO_CHROMA_AUTH_CREDENTIALS }}
            CHROMA_AUTH_PROVIDER=${{ env.DEMO_CHROMA_AUTH_PROVIDER }}
            CHROMA_URL=${{ env.DEMO_CHROMA_URL }}
            CHUNCK_SIZE=${{ env.DEMO_CHUNCK_SIZE }}
            CLAUDE_API_KEY=${{ env.DEMO_CLAUDE_API_KEY }}
            CONVERTO_EMAIL=${{ env.DEMO_CONVERTO_EMAIL }}
            CONVERTO_TRAIN_BUCKET_NAME=${{ env.DEMO_CONVERTO_TRAIN_BUCKET_NAME }}
            COVERTO_PIC_BUCKET_NAME=${{ env.DEMO_COVERTO_PIC_BUCKET_NAME }}
            CRYPTO_ENCRYPTION_SECRET=${{ env.DEMO_CRYPTO_ENCRYPTION_SECRET }}
            DATABASE_URL=${{ env.DEMO_DATABASE_URL_BASE }}
            EMBEDDING_PROVIDER=${{ env.DEMO_EMBEDDING_PROVIDER }}
            GOOGLE_CLIENT_ID=${{ env.DEMO_GOOGLE_CLIENT_ID }}
            HOST_PORT=${{ env.DEMO_HOST_PORT }}
            HOST_URL=${{ env.DEMO_HOST_URL }}
            IP_DATA_KEY=${{ env.DEMO_IP_DATA_KEY }}
            JWT_SECRET=${{ env.DEMO_JWT_SECRET }}
            LLM_PROVIDER=${{ env.DEMO_LLM_PROVIDER }}
            MAX_SMTP_CONNECTIONS=${{ env.DEMO_MAX_SMTP_CONNECTIONS }}
            MAX_TOTAL_FILE_SIZE=${{ env.DEMO_MAX_TOTAL_FILE_SIZE }}
            NAME=${{ env.DEMO_NAME }}
            NODE_ENV=${{ env.DEMO_NODE_ENV }}
            OPENAI_API_KEY=${{ env.DEMO_OPENAI_API_KEY }}
            OPENAI_ASSISTANT_DEFAULT_MODEL=${{ env.DEMO_OPENAI_ASSISTANT_DEFAULT_MODEL }}
            OPEN_AI_EMBEDDING_MODEL=${{ env.DEMO_OPEN_AI_EMBEDDING_MODEL }}
            OPEN_AI_MODEL=${{ env.DEMO_OPEN_AI_MODEL }}
            QUICK_MAIL_VALIDATOR_API=${{ env.DEMO_QUICK_MAIL_VALIDATOR_API }}
            REDIS_IP=${{ env.DEMO_REDIS_IP }}
            REDIS_PASSWORD=${{ env.DEMO_REDIS_PASSWORD }}
            REDIS_PORT=${{ env.DEMO_REDIS_PORT }}
            SENDGRID_KEY=${{ env.DEMO_SENDGRID_KEY }}
            SIGNUP_ALERT_MAIL=${{ env.DEMO_SIGNUP_ALERT_MAIL }}
            SUPER_USER_EMAIL=${{ env.DEMO_SUPER_USER_EMAIL }}
            SUPER_user=${{ env.DEMO_SUPER_user }}
            SUPER_USER_PASSWORD=${{ env.DEMO_SUPER_USER_PASSWORD }}
            TRAINING_CONTENT_PATH=${{ env.DEMO_TRAINING_CONTENT_PATH }}
            UPLOADS_FOLDER=${{ env.DEMO_UPLOADS_FOLDER }}
            VERIFICATION_EXPIRES_IN=${{ env.DEMO_VERIFICATION_EXPIRES_IN }}
            ZAUTO_API_BASE_URL=${{ env.DEMO_ZAUTO_API_BASE_URL }}

      - name: Build and push Docker image for crm
        if: contains(github.event.head_commit.message, 'crm')
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64/v8
          context: ./crm
          file: ./crm/Dockerfile
          tags: |
            ghcr.io/zautoai/converto:demo-crm${{ github.sha }}
            ghcr.io/zautoai/converto:demo-crm
          build-args: |
            REDIS_IP=${{ env.DEMO_REDIS_IP }}
            REDIS_PASSWORD=${{ env.DEMO_REDIS_PASSWORD }}
            REDIS_PORT=${{ env.DEMO_REDIS_PORT }}
            CRM_ACCESS_TOKEN=${{ env.DEMO_CRM_ACCESS_TOKEN }}
            CRM_API_PORT=${{ env.DEMO_CRM_API_PORT }}
            CRM_BASE_URL=${{ env.DEMO_CRM_BASE_URL }}
            CRM_DATABASE_URL=${{ env.DEMO_CRM_DATABASE_URL }}
            CRM_HOST=${{ env.DEMO_CRM_HOST }}
            CRM_HOST_PORT=${{ env.DEMO_CRM_HOST_PORT }}
            CRM_JWT_SECRET=${{ env.DEMO_CRM_JWT_SECRET }}

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::319221427139:role/GITHUB_EC2
          role-session-name: GitHubActions
          aws-region: ${{ env.DEMO_AWS_REGION }}

      - name: Insert Redis Password
        run: |
          sed -i'' -e "s|REDIS_PASSWORD_PLACEHOLDER|${{ env.DEMO_REDIS_PASSWORD }}|g" docker-compose.yml

      - name: Copy Updated Docker Compose File to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.DEV_EC2_HOST }}
          username: ${{ env.DEV_EC2_USER }}
          key: ${{ env.DEV_EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/converto/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEV_EC2_HOST }}
          username: ${{ env.DEV_EC2_USER }}
          key: ${{ env.DEV_EC2_SSH_KEY }}
          script: |
            set -x
            docker login ghcr.io -u ${{ secrets.DEMO_GITHUB_USER }} -p ${{ secrets.DEMO_GITHUB_TOKEN }}
            cd /home/ubuntu/converto
            docker-compose pull
            docker-compose up -d
            docker image prune -a -f

      - name: Check Health of test Redis Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEV_EC2_HOST }}
          username: ${{ env.DEV_EC2_USER }}
          key: ${{ env.DEV_EC2_SSH_KEY }}
          script: |
            set -x
            REDIS_CONTAINER="converto-redis-1"
            REDIS_PASSWORD=${{ env.DEMO_REDIS_PASSWORD }}
            REDIS_HEALTH=$(docker exec $REDIS_CONTAINER redis-cli -a $REDIS_PASSWORD PING)
            if [ "$REDIS_HEALTH" != "PONG" ]; then
              echo "Redis container $REDIS_CONTAINER is not healthy😭"
              exit 1
            else
              echo "Redis container $REDIS_CONTAINER is healthy😂"
            fi

      - name: Check Health of Base Application Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEV_EC2_HOST }}
          username: ${{ env.DEV_EC2_USER }}
          key: ${{ env.DEV_EC2_SSH_KEY }}
          script: |
            set -x
            BASE_APP_CONTAINER="converto-base-1"
            HEALTH_CHECK_URL="http://localhost:3000/health"
            if curl --fail $HEALTH_CHECK_URL; then
              echo "Container $BASE_APP_CONTAINER is healthy"
            else
              echo "Container $BASE_APP_CONTAINER is not healthy😭"
              exit 1
            fi

      - name: Check Health of CRM Application Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEV_EC2_HOST }}
          username: ${{ env.DEV_EC2_USER }}
          key: ${{ env.DEV_EC2_SSH_KEY }}
          script: |
            set -x
            CRM_APP_CONTAINER="converto-crm-1"
            HEALTH_CHECK_URL="http://localhost:3001/api/v1/ping"
            if curl --fail $HEALTH_CHECK_URL; then
              echo "Container $CRM_APP_CONTAINER is healthy"
            else
              echo "Container $CRM_APP_CONTAINER is not healthy😭."
              exit 1
            fi

      - name: Deployment Success Message
        run: echo "Deployment completed successfully!🎉😂"
