name: Deploy to AWS EC2

on:
  push:
    branches: [ dev ]
    paths:
      - 'base/**'
      - 'crm/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [COMMON, Dev]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.LOGIN_GITHUB_USER }}
        password: ${{ secrets.LOGIN_GITHUB_TOKEN }}
    - name: Build and push Docker image for base
      if: contains(github.event.head_commit.message, 'base')
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./base
        file: ./base/Dockerfile
        tags: |
          ghcr.io/zautoai/converto:dev-base${{ github.sha }}
          ghcr.io/zautoai/converto:dev-base
        build-args: |
          APOLLO_API_KEY=${{ secrets[format('{0}_APOLLO_API_KEY', matrix.environment)] }}
          AWS_ACCESS_KEY_ID=${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', matrix.environment)] }}
          AWS_REGION=${{ secrets[format('{0}_AWS_REGION', matrix.environment)] }}
          AWS_SECRET_ACCESS_KEY=${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', matrix.environment)] }}
          CHROMA_AUTH_CREDENTIALS=${{ secrets[format('{0}_CHROMA_AUTH_CREDENTIALS', matrix.environment)] }}
          CHROMA_AUTH_PROVIDER=${{ secrets[format('{0}_CHROMA_AUTH_PROVIDER', matrix.environment)] }}
          CHROMA_URL=${{ secrets[format('{0}_CHROMA_URL', matrix.environment)] }}
          CHUNCK_SIZE=${{ secrets[format('{0}_CHUNCK_SIZE', matrix.environment)] }}
          CLAUDE_API_KEY=${{ secrets[format('{0}_CLAUDE_API_KEY', matrix.environment)] }}
          COHERE_API_KEY=${{ secrets[format('{0}_COHERE_API_KEY', matrix.environment)] }}
          CONVERTO_EMAIL=${{ secrets[format('{0}_CONVERTO_EMAIL', matrix.environment)] }}
          CONVERTO_TRAIN_BUCKET_NAME=${{ secrets[format('{0}_CONVERTO_TRAIN_BUCKET_NAME', matrix.environment)] }}
          COVERTO_PIC_BUCKET_NAME=${{ secrets[format('{0}_COVERTO_PIC_BUCKET_NAME', matrix.environment)] }}
          CRYPTO_ENCRYPTION_SECRET=${{ secrets[format('{0}_CRYPTO_ENCRYPTION_SECRET', matrix.environment)] }}
          DATABASE_URL=${{ secrets[format('{0}_DATABASE_URL_BASE', matrix.environment)] }}
          EMBEDDING_PROVIDER=${{ secrets[format('{0}_EMBEDDING_PROVIDER', matrix.environment)] }}
          GOOGLE_CLIENT_ID=${{ secrets[format('{0}_GOOGLE_CLIENT_ID', matrix.environment)] }}
          HOST_PORT=${{ secrets[format('{0}_HOST_PORT', matrix.environment)] }}
          HOST_URL=${{ secrets[format('{0}_HOST_URL', matrix.environment)] }}
          IP_DATA_KEY=${{ secrets[format('{0}_IP_DATA_KEY', matrix.environment)] }}
          JWT_SECRET=${{ secrets[format('{0}_JWT_SECRET', matrix.environment)] }}
          LLM_PROVIDER=${{ secrets[format('{0}_LLM_PROVIDER', matrix.environment)] }}
          MAX_SMTP_CONNECTIONS=${{ secrets[format('{0}_MAX_SMTP_CONNECTIONS', matrix.environment)] }}
          MAX_TOTAL_FILE_SIZE=${{ secrets[format('{0}_MAX_TOTAL_FILE_SIZE', matrix.environment)] }}
          NAME=${{ secrets[format('{0}_NAME', matrix.environment)] }}
          NODE_ENV=${{ secrets[format('{0}_NODE_ENV', matrix.environment)] }}
          OPENAI_API_KEY=${{ secrets[format('{0}_OPENAI_API_KEY', matrix.environment)] }}
          OPENAI_ASSISTANT_DEFAULT_MODEL=${{ secrets[format('{0}_OPENAI_ASSISTANT_DEFAULT_MODEL', matrix.environment)] }}
          OPEN_AI_EMBEDDING_MODEL=${{ secrets[format('{0}_OPEN_AI_EMBEDDING_MODEL', matrix.environment)] }}
          OPEN_AI_MODEL=${{ secrets[format('{0}_OPEN_AI_MODEL', matrix.environment)] }}
          QUICK_MAIL_VALIDATOR_API=${{ secrets[format('{0}_QUICK_MAIL_VALIDATOR_API', matrix.environment)] }}
          REDIS_IP=${{ secrets[format('{0}_REDIS_IP', matrix.environment)] }}
          REDIS_PASSWORD=${{ secrets[format('{0}_REDIS_PASSWORD', matrix.environment)] }}
          REDIS_PORT=${{ secrets[format('{0}_REDIS_PORT', matrix.environment)] }}
          SENDGRID_KEY=${{ secrets[format('{0}_SENDGRID_KEY', matrix.environment)] }}
          SERVER_HOST=${{ secrets[format('{0}_SERVER_HOST', matrix.environment)] }}
          SERVER_SSH_KEY=${{ secrets[format('{0}_SERVER_SSH_KEY', matrix.environment)] }}
          SERVER_USER=${{ secrets[format('{0}_SERVER_USER', matrix.environment)] }}
          SIGNUP_ALERT_MAIL=${{ secrets[format('{0}_SIGNUP_ALERT_MAIL', matrix.environment)] }}
          SUPER_USER_EMAIL=${{ secrets[format('{0}_SUPER_USER_EMAIL', matrix.environment)] }}
          SUPER_USER=${{ secrets[format('{0}_SUPER_USER', matrix.environment)] }}
          SUPER_USER_PASSWORD=${{ secrets[format('{0}_SUPER_USER_PASSWORD', matrix.environment)] }}
          TRAINING_CONTENT_PATH=${{ secrets[format('{0}_TRAINING_CONTENT_PATH', matrix.environment)] }}
          UPLOADS_FOLDER=${{ secrets[format('{0}_UPLOADS_FOLDER', matrix.environment)] }}
          VERIFICATION_EXPIRES_IN=${{ secrets[format('{0}_VERIFICATION_EXPIRES_IN', matrix.environment)] }}
          ZAUTO_API_BASE_URL=${{ secrets[format('{0}_ZAUTO_API_BASE_URL', matrix.environment)] }}

    - name: Build and push Docker image for crm
      if: contains(github.event.head_commit.message, 'crm')
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./crm
        file: ./crm/Dockerfile
        tags: |
          ghcr.io/zautoai/converto:dev-crm${{ github.sha }}
          ghcr.io/zautoai/converto:dev-crm
        build-args: |
          REDIS_IP=${{ secrets[format('{0}_REDIS_IP', matrix.environment)] }}
          REDIS_PASSWORD=${{ secrets[format('{0}_REDIS_PASSWORD', matrix.environment)] }}
          REDIS_PORT=${{ secrets[format('{0}_REDIS_PORT', matrix.environment)] }}
          CRM_ACCESS_TOKEN=${{ secrets[format('{0}_CRM_ACCESS_TOKEN', matrix.environment)] }}
          CRM_API_PORT=${{ secrets[format('{0}_CRM_API_PORT', matrix.environment)] }}
          CRM_BASE_URL=${{ secrets[format('{0}_CRM_BASE_URL', matrix.environment)] }}
          CRM_DATABASE_URL=${{ secrets[format('{0}_CRM_DATABASE_URL', matrix.environment)] }}
          CRM_HOST=${{ secrets[format('{0}_CRM_HOST', matrix.environment)] }}
          CRM_HOST_PORT=${{ secrets[format('{0}_CRM_HOST_PORT', matrix.environment)] }}
          CRM_JWT_SECRET=${{ secrets[format('{0}_CRM_JWT_SECRET', matrix.environment)] }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        environment: [COMMON, Dev]
    steps:
    - uses: actions/checkout@v2
    - name: Insert Redis Password
      run: |
        sed -i'' -e "s|REDIS_PASSWORD_PLACEHOLDER|${{ secrets[format('{0}_REDIS_PASSWORD', matrix.environment)] }}|g" docker-compose.yml

    - name: Show Updated Docker Compose File
      run: cat docker-compose.yml
    - name: Copy Updated Docker Compose File to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets[format('{0}_SERVER_HOST', matrix.environment)] }}
        username: ${{ secrets[format('{0}_SERVER_USER', matrix.environment)] }}
        key: ${{ secrets[format('{0}_SERVER_SSH_KEY', matrix.environment)] }}
        source: "docker-compose.yml"
        target: "/home/dbserver/converto/"
    - name: Deploy to Local Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets[format('{0}_SERVER_HOST', matrix.environment)] }}
        username: ${{ secrets[format('{0}_SERVER_USER', matrix.environment)] }}
        key: ${{ secrets[format('{0}_SERVER_SSH_KEY', matrix.environment)] }}
        script: |
          set -x  # Enable debugging
          docker login ghcr.io -u ${{ secrets.LOGIN_GITHUB_USER }} -p ${{ secrets.LOGIN_GITHUB_TOKEN }}
          cd /home/dbserver/converto
          cat docker-compose.yml
          docker-compose pull
          docker-compose up -d
          docker image prune -a -f

    - name: Check Health of test Redis Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets[format('{0}_SERVER_HOST', matrix.environment)] }}
        username: ${{ secrets[format('{0}_SERVER_USER', matrix.environment)] }}
        key: ${{ secrets[format('{0}_SERVER_SSH_KEY', matrix.environment)] }}
        script: |
          set -x
          REDIS_CONTAINER="converto-redis-1"
          REDIS_PASSWORD=${{ secrets[format('{0}_REDIS_PASSWORD', matrix.environment)] }}
          REDIS_HEALTH=$(docker exec $REDIS_CONTAINER redis-cli -a $REDIS_PASSWORD PING)
          if [ "$REDIS_HEALTH" != "PONG" ]; then
          echo "Redis container $REDIS_CONTAINER is not healthy😭"
          exit 1
          else
          echo "Redis container $REDIS_CONTAINER is healthy😂"
          fi

    - name: Check Health of Base Application Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets[format('{0}_SERVER_HOST', matrix.environment)] }}
        username: ${{ secrets[format('{0}_SERVER_USER', matrix.environment)] }}
        key: ${{ secrets[format('{0}_SERVER_SSH_KEY', matrix.environment)] }}
        script: |
          BASE_APP_CONTAINER="converto-base-1"
          HEALTH_CHECK_URL="http://localhost:3000/health"
          if curl --fail $HEALTH_CHECK_URL; then
          echo "Container $BASE_APP_CONTAINER is healthy"
          else
          echo "Container $BASE_APP_CONTAINER is not healthy😭"
          exit 1
          fi

    - name: Check Health of CRM Application Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets[format('{0}_SERVER_HOST', matrix.environment)] }}
        username: ${{ secrets[format('{0}_SERVER_USER', matrix.environment)] }}
        key: ${{ secrets[format('{0}_SERVER_SSH_KEY', matrix.environment)] }}
        script: |
          CRM_APP_CONTAINER="converto-crm-1"
          HEALTH_CHECK_URL="http://localhost:3001/api/v1/ping"
          if curl --fail $HEALTH_CHECK_URL; then
          echo "Container $CRM_APP_CONTAINER is healthy"
          else
          echo "Container $CRM_APP_CONTAINER is not healthy😭"
          exit 1
          fi
    - name: Deployment Success Message
      run: echo "Deployment completed successfully!🎉"
