on:
  push:
    branches: [ prod ]
    paths:
      - 'base/**'
      - 'crm/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ GITHUB_USER }}
        password: ${{ GITHUB_TOKEN }}
    - name: Build and push Docker image for base
      if: contains(github.event.head_commit.message, 'base')
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./base
        file: ./base/Dockerfile
        tags: |
          ghcr.io/zautoai/converto:base${{ github.sha }}
          ghcr.io/zautoai/converto:base
        build-args: |
          APOLLO_API_KEY=${{ APOLLO_API_KEY }}
          AWS_ACCESS_KEY_ID=${{ AWS_ACCESS_KEY_ID }}
          AWS_REGION=${{ AWS_REGION }}
          AWS_SECRET_ACCESS_KEY=${{ AWS_SECRET_ACCESS_KEY }}
          CHROMA_AUTH_CREDENTIALS=${{ CHROMA_AUTH_CREDENTIALS }}
          CHROMA_AUTH_PROVIDER=${{ CHROMA_AUTH_PROVIDER }}
          CHROMA_URL=${{ CHROMA_URL }}
          CHUNCK_SIZE=${{ CHUNCK_SIZE }}
          CLAUDE_API_KEY=${{ CLAUDE_API_KEY }}
          COHERE_API_KEY=${{ COHERE_API_KEY }}
          CONVERTO_EMAIL=${{ CONVERTO_EMAIL }}
          CONVERTO_TRAIN_BUCKET_NAME=${{ CONVERTO_TRAIN_BUCKET_NAME }}
          COVERTO_PIC_BUCKET_NAME=${{ COVERTO_PIC_BUCKET_NAME }}
          CRYPTO_ENCRYPTION_SECRET=${{ CRYPTO_ENCRYPTION_SECRET }}
          DATABASE_URL=${{ DATABASE_URL_BASE }}
          EMBEDDING_PROVIDER=${{ EMBEDDING_PROVIDER }}
          GITHUB_TOKEN=${{ GITHUB_TOKEN }}
          GITHUB_USER=${{ GITHUB_USER }}
          GOOGLE_CLIENT_ID=${{ GOOGLE_CLIENT_ID }}
          HOST_PORT=${{ HOST_PORT }}
          HOST_URL=${{ HOST_URL }}
          IP_DATA_KEY=${{ IP_DATA_KEY }}
          JWT_SECRET=${{ JWT_SECRET }}
          LLM_PROVIDER=${{ LLM_PROVIDER }}
          MAX_SMTP_CONNECTIONS=${{ MAX_SMTP_CONNECTIONS }}
          MAX_TOTAL_FILE_SIZE=${{ MAX_TOTAL_FILE_SIZE }}
          NAME=${{ NAME }}
          NODE_ENV=${{ NODE_ENV }}
          OPENAI_API_KEY=${{ OPENAI_API_KEY }}
          OPENAI_ASSISTANT_DEFAULT_MODEL=${{ OPENAI_ASSISTANT_DEFAULT_MODEL }}
          OPEN_AI_EMBEDDING_MODEL=${{ OPEN_AI_EMBEDDING_MODEL }}
          OPEN_AI_MODEL=${{ OPEN_AI_MODEL }}
          QUICK_MAIL_VALIDATOR_API=${{ QUICK_MAIL_VALIDATOR_API }}
          REDIS_IP=${{ REDIS_IP }}
          REDIS_PASSWORD=${{ REDIS_PASSWORD }}
          REDIS_PORT=${{ REDIS_PORT }}
          SENDGRID_KEY=${{ SENDGRID_KEY }}
          SERVER_HOST=${{ SERVER_HOST }}
          SERVER_SSH_KEY=${{ SERVER_SSH_KEY }}
          SERVER_USER=${{ SERVER_USER }}
          SIGNUP_ALERT_MAIL=${{ SIGNUP_ALERT_MAIL }}
          SUPER_USER_EMAIL=${{ SUPER_USER_EMAIL }}
          SUPER_user=${{ SUPER_user }}
          SUPER_USER_PASSWORD=${{ SUPER_USER_PASSWORD }}
          TRAINING_CONTENT_PATH=${{ TRAINING_CONTENT_PATH }}
          UPLOADS_FOLDER=${{ UPLOADS_FOLDER }}
          VERIFICATION_EXPIRES_IN=${{ VERIFICATION_EXPIRES_IN }}
          ZAUTO_API_BASE_URL=${{ ZAUTO_API_BASE_URL }}
    - name: Build and push Docker image for crm
      if: contains(github.event.head_commit.message, 'crm')
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./crm
        file: ./crm/Dockerfile
        tags: |
          ghcr.io/zautoai/converto:crm${{ github.sha }}
          ghcr.io/zautoai/converto:crm
        build-args: |
          REDIS_IP=${{ REDIS_IP }}
          REDIS_PASSWORD=${{ REDIS_PASSWORD }}
          REDIS_PORT=${{ REDIS_PORT }}
          CRM_ACCESS_TOKEN=${{ CRM_ACCESS_TOKEN }}
          CRM_API_PORT=${{ CRM_API_PORT }}
          CRM_BASE_URL=${{ CRM_BASE_URL }}
          CRM_DATABASE_URL=${{ CRM_DATABASE_URL }}
          CRM_HOST=${{ CRM_HOST }}
          CRM_HOST_PORT=${{ CRM_HOST_PORT }}
          CRM_JWT_SECRET=${{ CRM_JWT_SECRET }}

          deploy:
          DEPLOY_AWS_ACCESS_KEY_ID=${{secrets.DEPLOY_AWS_ACCESS_KEY_ID}}
          DEPLOY_AWS_SECRET_ACCESS_KEY=${{secrets.DEPLOY_AWS_SECRET_ACCESS_KEY}}
          DEPLOY_AWS_REGION=${{secrets. DEPLOY_AWS_REGION}}
