on:
  push:
    branches: [prod]
    paths:
      - 'base/**'
      - 'crm/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.LOGIN_GITHUB_TOKEN }}
        password: ${{ secrets.LOGIN_GITHUB_TOKEN }}
    - name: Build and push Docker image for base
      if: contains(github.event.head_commit.message, 'base')
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./base
        file: ./base/Dockerfile
        tags: |
          ghcr.io/zautoai/converto:prod-base${{ github.sha }}
          ghcr.io/zautoai/converto:prod-base
        build-args: |
          APOLLO_API_KEY=${{ secrets.APOLLO_API_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CHROMA_AUTH_CREDENTIALS=${{ secrets.CHROMA_AUTH_CREDENTIALS }}
          CHROMA_AUTH_PROVIDER=${{ secrets.CHROMA_AUTH_PROVIDER }}
          CHROMA_URL=${{ secrets.CHROMA_URL }}
          CHUNCK_SIZE=${{ secrets.CHUNCK_SIZE }}
          CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}
          COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}
          CONVERTO_EMAIL=${{ secrets.CONVERTO_EMAIL }}
          CONVERTO_TRAIN_BUCKET_NAME=${{ secrets.CONVERTO_TRAIN_BUCKET_NAME }}
          COVERTO_PIC_BUCKET_NAME=${{ secrets.COVERTO_PIC_BUCKET_NAME }}
          CRYPTO_ENCRYPTION_SECRET=${{ secrets.CRYPTO_ENCRYPTION_SECRET }}
          DATABASE_URL=${{ secrets.DATABASE_URL_BASE }}
          EMBEDDING_PROVIDER=${{ secrets.EMBEDDING_PROVIDER }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          HOST_PORT=${{ secrets.HOST_PORT }}
          HOST_URL=${{ secrets.HOST_URL }}
          IP_DATA_KEY=${{ secrets.IP_DATA_KEY }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          LLM_PROVIDER=${{ secrets.LLM_PROVIDER }}
          MAX_SMTP_CONNECTIONS=${{ secrets.MAX_SMTP_CONNECTIONS }}
          MAX_TOTAL_FILE_SIZE=${{ secrets.MAX_TOTAL_FILE_SIZE }}
          NODE_secrets=${{ secrets.NODE_secrets }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_DEFAULT_MODEL=${{ secrets.OPENAI_ASSISTANT_DEFAULT_MODEL }}
          OPEN_AI_EMBEDDING_MODEL=${{ secrets.OPEN_AI_EMBEDDING_MODEL }}
          OPEN_AI_MODEL=${{ secrets.OPEN_AI_MODEL }}
          QUICK_MAIL_VALIDATOR_API=${{ secrets.QUICK_MAIL_VALIDATOR_API }}
          REDIS_IP=${{ secrets.REDIS_IP }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          SENDGRID_KEY=${{ secrets.SENDGRID_KEY }}
          SIGNUP_ALERT_MAIL=${{ secrets.SIGNUP_ALERT_MAIL }}
          SUPER_USER_EMAIL=${{ secrets.SUPER_USER_EMAIL }}
          SUPER_USER=${{ secrets.SUPER_USER }}
          SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }}
          TRAINING_CONTENT_PATH=${{ secrets.TRAINING_CONTENT_PATH }}
          UPLOADS_FOLDER=${{ secrets.UPLOADS_FOLDER }}
          VERIFICATION_EXPIRES_IN=${{ secrets.VERIFICATION_EXPIRES_IN }}

    - name: Build and push Docker image for crm
      if: contains(github.event.head_commit.message, 'crm')
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./crm
        file: ./crm/Dockerfile
        tags: |
          ghcr.io/zautoai/converto:prod-crm${{ github.sha }}
          ghcr.io/zautoai/converto:prod-crm
        build-args: |
          REDIS_IP=${{ secrets.REDIS_IP }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          CRM_ACCESS_TOKEN=${{ secrets.CRM_ACCESS_TOKEN }}
          CRM_API_PORT=${{ secrets.CRM_API_PORT }}
          CRM_BASE_URL=${{ secrets.CRM_BASE_URL }}
          CRM_DATABASE_URL=${{ secrets.CRM_DATABASE_URL }}
          CRM_HOST=${{ secrets.CRM_HOST }}
          CRM_HOST_PORT=${{ secrets.CRM_HOST_PORT }}
          CRM_JWT_SECRET=${{ secrets.CRM_JWT_SECRET }}

  deploy-base:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v2
      - name: Insert Redis Password for Base
        run: |
          sed -i'' -e "s|REDIS_PASSWORD_PLACEHOLDER|${{ secrets.REDIS_PASSWORD }}|g" docker-compose-base.yml

      - name: Show Updated Docker Compose File for Base
        run: cat docker-compose-base.yml

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.DEPLOY_AWS_REGION }}

      - name: Deploy Base to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=Base" \
            --parameters 'commands=["docker login ghcr.io -u ${{ secrets.LOGIN_GITHUB_USER }} -p ${{ secrets.LOGIN_GITHUB_TOKEN }}", "cd /path/to/your/project", "docker-compose -f docker-compose-base.yml pull", "docker-compose -f docker-compose-base.yml up -d", "docker image prune -a -f"]'

      - name: Check Health of Base Application Container
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=Base" \
            --parameters 'commands=["BASE_APP_CONTAINER=converto-base-1", "HEALTH_CHECK_URL=http://localhost:3000/health", "if curl --fail $HEALTH_CHECK_URL; then echo Container $BASE_APP_CONTAINER is healthy; else echo Container $BASE_APP_CONTAINER is not healthy; exit 1; fi"]'

  deploy-crm:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v2
      - name: Insert Redis Password for CRM
        run: |
          sed -i'' -e "s|REDIS_PASSWORD_PLACEHOLDER|${{ secrets.REDIS_PASSWORD }}|g" docker-compose-crm.yml

      - name: Show Updated Docker Compose File for CRM
        run: cat docker-compose-crm.yml

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.DEPLOY_AWS_REGION }}

      - name: Deploy CRM to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=CRM" \
            --parameters 'commands=["docker login ghcr.io -u ${{ secrets.LOGIN_GITHUB_USER }} -p ${{ secrets.LOGIN_GITHUB_TOKEN }}", "cd /path/to/your/project", "docker-compose -f docker-compose-crm.yml pull", "docker-compose -f docker-compose-crm.yml up -d", "docker image prune -a -f"]'

      - name: Check Health of CRM Application Container
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=CRM" \
            --parameters 'commands=["CRM_APP_CONTAINER=converto-crm-1", "HEALTH_CHECK_URL=http://localhost:3001/api/v1/ping", "if curl --fail $HEALTH_CHECK_URL; then echo Container $CRM_APP_CONTAINER is healthy; else echo Container $CRM_APP_CONTAINER is not healthy; exit 1; fi"]'

  deployment-success:
    runs-on: ubuntu-latest
    needs: [deploy-base, deploy-crm]
    steps:
      - name: Deployment Success Message
        run: echo "Deployment completed successfully!"
