name: CI/CD Pipeline

on:
  push:
    branches: [ stage ]
    paths:
      - 'base/**'
      - 'crm/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ env.GITHUB_TOKEN }}
      - name: Build and push Docker image for base
        if: contains(github.event.head_commit.message, 'base')
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./base
          file: ./base/Dockerfile
          tags: |
            ghcr.io/zautoai/converto:stage-base${{ github.sha }}
            ghcr.io/zautoai/converto:stage-base
          build-args: |
            APOLLO_API_KEY=${{ env.APOLLO_API_KEY }}
            AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            AWS_REGION=${{ env.AWS_REGION }}
            AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
            CHROMA_AUTH_CREDENTIALS=${{ env.CHROMA_AUTH_CREDENTIALS }}
            CHROMA_AUTH_PROVIDER=${{ env.CHROMA_AUTH_PROVIDER }}
            CHROMA_URL=${{ env.CHROMA_URL }}
            CHUNCK_SIZE=${{ env.CHUNCK_SIZE }}
            CLAUDE_API_KEY=${{ env.CLAUDE_API_KEY }}
            COHERE_API_KEY=${{ env.COHERE_API_KEY }}
            CONVERTO_EMAIL=${{ env.CONVERTO_EMAIL }}
            CONVERTO_TRAIN_BUCKET_NAME=${{ env.CONVERTO_TRAIN_BUCKET_NAME }}
            COVERTO_PIC_BUCKET_NAME=${{ env.COVERTO_PIC_BUCKET_NAME }}
            CRYPTO_ENCRYPTION_SECRET=${{ env.CRYPTO_ENCRYPTION_SECRET }}
            DATABASE_URL=${{ env.DATABASE_URL_BASE }}
            EMBEDDING_PROVIDER=${{ env.EMBEDDING_PROVIDER }}
            GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
            HOST_PORT=${{ env.HOST_PORT }}
            HOST_URL=${{ env.HOST_URL }}
            IP_DATA_KEY=${{ env.IP_DATA_KEY }}
            JWT_SECRET=${{ env.JWT_SECRET }}
            LLM_PROVIDER=${{ env.LLM_PROVIDER }}
            MAX_SMTP_CONNECTIONS=${{ env.MAX_SMTP_CONNECTIONS }}
            MAX_TOTAL_FILE_SIZE=${{ env.MAX_TOTAL_FILE_SIZE }}
            NODE_ENV=${{ env.NODE_ENV }}
            OPENAI_API_KEY=${{ env.OPENAI_API_KEY }}
            OPENAI_ASSISTANT_DEFAULT_MODEL=${{ env.OPENAI_ASSISTANT_DEFAULT_MODEL }}
            OPEN_AI_EMBEDDING_MODEL=${{ env.OPEN_AI_EMBEDDING_MODEL }}
            OPEN_AI_MODEL=${{ env.OPEN_AI_MODEL }}
            QUICK_MAIL_VALIDATOR_API=${{ env.QUICK_MAIL_VALIDATOR_API }}
            REDIS_IP=${{ env.REDIS_IP }}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            REDIS_PORT=${{ env.REDIS_PORT }}
            SENDGRID_KEY=${{ env.SENDGRID_KEY }}
            SIGNUP_ALERT_MAIL=${{ env.SIGNUP_ALERT_MAIL }}
            SUPER_USER_EMAIL=${{ env.SUPER_USER_EMAIL }}
            SUPER_USER=${{ env.SUPER_USER }}
            SUPER_USER_PASSWORD=${{ env.SUPER_USER_PASSWORD }}
            TRAINING_CONTENT_PATH=${{ env.TRAINING_CONTENT_PATH }}
            UPLOADS_FOLDER=${{ env.UPLOADS_FOLDER }}
            VERIFICATION_EXPIRES_IN=${{ env.VERIFICATION_EXPIRES_IN }}


      - name: Build and push Docker image for crm
        if: contains(github.event.head_commit.message, 'crm')
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./crm
          file: ./crm/Dockerfile
          tags: |
            ghcr.io/zautoai/converto:stage-crm${{ github.sha }}
            ghcr.io/zautoai/converto:stage-crm
          build-args: |
            REDIS_IP=${{ secrets.REDIS_IP }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
            CRM_HOST=${{ secrets.CRM_HOST }}
            CRM_HOST_PORT=${{ secrets.CRM_HOST_PORT }}
            CRM_JWT_SECRET=${{ secrets.CRM_JWT_SECRET }}
            CRM_HUBSPOT_CLIENT_ID=${{ secrets.CRM_HUBSPOT_CLIENT_ID }}
            CRM_HUBSPOT_CLIENT_SECRET=${{ secrets.CRM_HUBSPOT_CLIENT_SECRET }}
            CRM_HUBSPOT_REDIRECT_URI=${{ CRM_HUBSPOT_REDIRECT_URI }}

  deploy-base:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        stage_base: [1, 2, 3]  # Define your update groups
    steps:
      - uses: actions/checkout@v2
      - name: Insert Redis Password for Base
        run: |
          sed -i'' -e "s|REDIS_PASSWORD_PLACEHOLDER|${{ env.REDIS_PASSWORD }}|g" docker-compose-base.yml

      - name: Show Updated Docker Compose File for Base
        run: cat docker-compose-base.yml
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ env.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.DEPLOY_AWS_REGION }}

      - name: Deploy Base to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=Base" "Key=tag:UpdateGroup,Values=${{ matrix.update_group }}" \
            --parameters 'commands=["docker login ghcr.io -u ${{ secrets.GITHUB_USER }} -p ${{ secrets.GITHUB_TOKEN }}", "cd ./home/ubuntu/converto", "docker-compose -f docker-compose-base.yml pull", "docker-compose -f docker-compose-base.yml up -d", "docker image prune -a -f"]'

      - name: Check Health of Base Application Container
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=Base" "Key=tag:UpdateGroup,Values=${{ matrix.update_group }}" \
            --parameters 'commands=["BASE_APP_CONTAINER=converto-base-1", "HEALTH_CHECK_URL=http://localhost:3000/health", "if curl --fail $HEALTH_CHECK_URL; then echo Container $BASE_APP_CONTAINER is healthy; else echo Container $BASE_APP_CONTAINER is not healthy😭; exit 1; fi"]'

  deploy-crm:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        stage_crm: [1, 2, 3]  # Define your update groups
    steps:
      - uses: actions/checkout@v2
      - name: Insert Redis Password for CRM
        run: |
          sed -i'' -e "s|REDIS_PASSWORD_PLACEHOLDER|${{ env.REDIS_PASSWORD }}|g" docker-compose-crm.yml

      - name: Show Updated Docker Compose File for CRM
        run: cat docker-compose-crm.yml
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ env.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.DEPLOY_AWS_REGION }}

      - name: Deploy CRM to EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=CRM" "Key=tag:UpdateGroup,Values=${{ matrix.update_group }}" \
            --parameters 'commands=["docker login ghcr.io -u ${{ env.GITHUB_USER }} -p ${{ secrets.GITHUB_TOKEN }}", "cd /path/to/your/project", "docker-compose -f docker-compose-crm.yml pull", "docker-compose -f docker-compose-crm.yml up -d", "docker image prune -a -f"]'

      - name: Check Health of CRM Application Container
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Role,Values=CRM" "Key=tag:UpdateGroup,Values=${{ matrix.update_group }}" \
            --parameters 'commands=["CRM_APP_CONTAINER=converto-crm-1", "HEALTH_CHECK_URL=http://localhost:3001/api/v1/ping", "if curl --fail $HEALTH_CHECK_URL; then echo Container $CRM_APP_CONTAINER is healthy; else echo Container $CRM_APP_CONTAINER is not healthy😭; exit 1; fi"]'

  deployment-success:
    runs-on: ubuntu-latest
    needs: [deploy-base, deploy-crm]
    steps:
      - name: Deployment Success Message
        run: echo "Deployment completed successfully!🎉"
